        route:
          group_by: ['alertname', 'cluster', 'service']
          group_wait: 5s
          group_interval: 10s
          repeat_interval: 30s
          receiver: scale-up
          routes:
            - match:
                action: firewall-block
              receiver: firewall-blocker
        receivers:
          - name: 'scale-up'
            webhook_configs:
              - url: http://gateway.openfaas:8080/system/alert
                send_resolved: true
                http_config:
                  basic_auth:
                    username: admin
                    password_file: /var/secrets/basic-auth-password
          - name: 'firewall-blocker'
            webhook_configs:
              - url: http://localhost:5000/block
                send_resolved: false
                http_config:
                  basic_auth:
                    username: admin
                    password: "admin"