{
 "title": "Monitorización OpenFaaS",
 "time": { "from": "2024-10-06T17:27:21.283Z", "to": "2024-10-07T17:27:21.295Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=~\"$namespace\"}, container_label_io_kubernetes_pod_name)"
    }
   },
   {
    "name": "function",
    "query": {
     "query": "label_values(gateway_service_count, function_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container_label_io_kubernetes_pod_name) (container_memory_working_set_bytes{container_label_io_kubernetes_pod_namespace=~\"$namespace\", image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(container_label_io_kubernetes_pod_name) (rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_namespace=~\"$namespace\", image!=\"\"}[20s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(rate(gateway_functions_seconds_sum{function_name=~\"$function\"}[5s]) / rate(gateway_functions_seconds_count{function_name=~\"$function\"}[5s]))\r\n",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "gateway_service_count{function_name=~\"$function\"}",
     "legendFormat": "{{function_name}}"
    }
   ]
  }
 ]
}