function createlegend(axes1)
%CREATELEGEND(axes1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 13-Jun-2024 18:17:07

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.910894114780757 0.25181709067736 0.0717447925855716 0.673808331905466]);

