apiVersion: v1
kind: Service
metadata:
  name: firewall-external
spec:
  type: NodePort
  selector:
    app: firewall-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000